server:
  port: 8091
  tomcat:
    max-http-header-size: 10240 #单位：字节
  servlet:
    context-path: /exch_platform

exch:
  swagger-open: true                #是否开启swagger (true/false)
  kaptcha-open: false               #是否开启登录时验证码 (true/false)
  #  file-upload-path: d:/tmp     #文件上传目录(不配置的话为java.io.tmpdir目录)
  spring-session-open: false        #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒

beetl:
  resource-auto-check: @resource.auto@  #热加载beetl模板，开发时候用

spring:
  profiles:
    active: @spring.active@
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理


mybatis-plus:
  mapper-locations: classpath*:com/exch/platform/**/mapping/*.xml
  typeAliasesPackage: com.exch.platform.modular.*.model,com.exch.platform.modular.*.entity
  global-config:
    metaObject-handler: com.exch.platform.core.metadata.ExchMpFieldHandler

log:
  path: exch-logs
