### 本地、测试通用配置

############## sftp 配置 ##############
sftp:
  host: 10.20.88.21
  username: mysftp
  password: mysftp
  port: 22
  filepath: upload/exch/


############## redis 配置 ##############
#redis:
#  pool:
#    max-active: 200
#    max-wait: -1
#    max-idle: 8
#    min-idle: 0
#  timeout: 0
#  database: 1
#  password: 123456789
#  sentinel:
#    master: testre
#    nodes: 10.18.9.21
#    port: 26380

############## rabbitMQ 配置 ##############
spring:
  rabbitmq:
    host: 10.20.88.21
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: MANUAL
      simple:
        acknowledge-mode: MANUAL
        default-requeue-rejected: false #重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）
        retry:
          max-attempts: 5 #最大重试次数
          enabled: true #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          #initial-interval: 100l #重试间隔时间（单位毫秒）
